extern "C" void RTExceptions_DefaultErrorCatch(void);
extern "C" void _M2_Storage_init (int argc, char *argv[]);
extern "C" void _M2_Storage_finish (void);
extern "C" void _M2_SYSTEM_init (int argc, char *argv[]);
extern "C" void _M2_SYSTEM_finish (void);
extern "C" void _M2_M2RTS_init (int argc, char *argv[]);
extern "C" void _M2_M2RTS_finish (void);
extern "C" void _M2_RTExceptions_init (int argc, char *argv[]);
extern "C" void _M2_RTExceptions_finish (void);
extern "C" void _M2_IOLink_init (int argc, char *argv[]);
extern "C" void _M2_IOLink_finish (void);
extern "C" void _M2_Indexing_init (int argc, char *argv[]);
extern "C" void _M2_Indexing_finish (void);
extern "C" void _M2_NumberIO_init (int argc, char *argv[]);
extern "C" void _M2_NumberIO_finish (void);
extern "C" void _M2_StrLib_init (int argc, char *argv[]);
extern "C" void _M2_StrLib_finish (void);
extern "C" void _M2_FIO_init (int argc, char *argv[]);
extern "C" void _M2_FIO_finish (void);
extern "C" void _M2_errno_init (int argc, char *argv[]);
extern "C" void _M2_errno_finish (void);
extern "C" void _M2_termios_init (int argc, char *argv[]);
extern "C" void _M2_termios_finish (void);
extern "C" void _M2_IO_init (int argc, char *argv[]);
extern "C" void _M2_IO_finish (void);
extern "C" void _M2_StdIO_init (int argc, char *argv[]);
extern "C" void _M2_StdIO_finish (void);
extern "C" void _M2_ErrnoCategory_init (int argc, char *argv[]);
extern "C" void _M2_ErrnoCategory_finish (void);
extern "C" void _M2_Debug_init (int argc, char *argv[]);
extern "C" void _M2_Debug_finish (void);
extern "C" void _M2_IOConsts_init (int argc, char *argv[]);
extern "C" void _M2_IOConsts_finish (void);
extern "C" void _M2_RTio_init (int argc, char *argv[]);
extern "C" void _M2_RTio_finish (void);
extern "C" void _M2_SysExceptions_init (int argc, char *argv[]);
extern "C" void _M2_SysExceptions_finish (void);
extern "C" void _M2_SysStorage_init (int argc, char *argv[]);
extern "C" void _M2_SysStorage_finish (void);
extern "C" void _M2_RTgen_init (int argc, char *argv[]);
extern "C" void _M2_RTgen_finish (void);
extern "C" void _M2_RTgenif_init (int argc, char *argv[]);
extern "C" void _M2_RTgenif_finish (void);
extern "C" void _M2_ChanConsts_init (int argc, char *argv[]);
extern "C" void _M2_ChanConsts_finish (void);
extern "C" void _M2_ASCII_init (int argc, char *argv[]);
extern "C" void _M2_ASCII_finish (void);
extern "C" void _M2_M2EXCEPTION_init (int argc, char *argv[]);
extern "C" void _M2_M2EXCEPTION_finish (void);
extern "C" void _M2_StdChans_init (int argc, char *argv[]);
extern "C" void _M2_StdChans_finish (void);
extern "C" void _M2_StrIO_init (int argc, char *argv[]);
extern "C" void _M2_StrIO_finish (void);
extern "C" void _M2_RTentity_init (int argc, char *argv[]);
extern "C" void _M2_RTentity_finish (void);
extern "C" void _M2_ldtoa_init (int argc, char *argv[]);
extern "C" void _M2_ldtoa_finish (void);
extern "C" void _M2_dtoa_init (int argc, char *argv[]);
extern "C" void _M2_dtoa_finish (void);
extern "C" void _M2_Assertion_init (int argc, char *argv[]);
extern "C" void _M2_Assertion_finish (void);
extern "C" void _M2_ConvTypes_init (int argc, char *argv[]);
extern "C" void _M2_ConvTypes_finish (void);
extern "C" void _M2_IOChan_init (int argc, char *argv[]);
extern "C" void _M2_IOChan_finish (void);
extern "C" void _M2_CharClass_init (int argc, char *argv[]);
extern "C" void _M2_CharClass_finish (void);
extern "C" void _M2_EXCEPTIONS_init (int argc, char *argv[]);
extern "C" void _M2_EXCEPTIONS_finish (void);
extern "C" void _M2_DynamicStrings_init (int argc, char *argv[]);
extern "C" void _M2_DynamicStrings_finish (void);
extern "C" void _M2_WholeConv_init (int argc, char *argv[]);
extern "C" void _M2_WholeConv_finish (void);
extern "C" void _M2_StringConvert_init (int argc, char *argv[]);
extern "C" void _M2_StringConvert_finish (void);
extern "C" void _M2_gdbif_init (int argc, char *argv[]);
extern "C" void _M2_gdbif_finish (void);
extern "C" void _M2_RTdata_init (int argc, char *argv[]);
extern "C" void _M2_RTdata_finish (void);
extern "C" void _M2_WholeStr_init (int argc, char *argv[]);
extern "C" void _M2_WholeStr_finish (void);
extern "C" void _M2_wrapsock_init (int argc, char *argv[]);
extern "C" void _M2_wrapsock_finish (void);
extern "C" void _M2_wrapc_init (int argc, char *argv[]);
extern "C" void _M2_wrapc_finish (void);
extern "C" void _M2_RTfio_init (int argc, char *argv[]);
extern "C" void _M2_RTfio_finish (void);
extern "C" void _M2_GC_init (int argc, char *argv[]);
extern "C" void _M2_GC_finish (void);
extern "C" void _M2_Strings_init (int argc, char *argv[]);
extern "C" void _M2_Strings_finish (void);
extern "C" void _M2_ComplexMath_init (int argc, char *argv[]);
extern "C" void _M2_ComplexMath_finish (void);
extern "C" void _M2_Selective_init (int argc, char *argv[]);
extern "C" void _M2_Selective_finish (void);
extern "C" void _M2_coord_init (int argc, char *argv[]);
extern "C" void _M2_coord_finish (void);
extern "C" void _M2_MathLib0_init (int argc, char *argv[]);
extern "C" void _M2_MathLib0_finish (void);
extern "C" void _M2_RawIO_init (int argc, char *argv[]);
extern "C" void _M2_RawIO_finish (void);
extern "C" void _M2_Fractions_init (int argc, char *argv[]);
extern "C" void _M2_Fractions_finish (void);
extern "C" void _M2_Builtins_init (int argc, char *argv[]);
extern "C" void _M2_Builtins_finish (void);
extern "C" void _M2_roots_init (int argc, char *argv[]);
extern "C" void _M2_roots_finish (void);
extern "C" void _M2_Points_init (int argc, char *argv[]);
extern "C" void _M2_Points_finish (void);
extern "C" void _M2_ClientSocket_init (int argc, char *argv[]);
extern "C" void _M2_ClientSocket_finish (void);
extern "C" void _M2_SeqFile_init (int argc, char *argv[]);
extern "C" void _M2_SeqFile_finish (void);
extern "C" void _M2_MemStream_init (int argc, char *argv[]);
extern "C" void _M2_MemStream_finish (void);
extern "C" void _M2_deviceIf_init (int argc, char *argv[]);
extern "C" void _M2_deviceIf_finish (void);
extern "C" void _M2_polar_init (int argc, char *argv[]);
extern "C" void _M2_polar_finish (void);
extern "C" void _M2_history_init (int argc, char *argv[]);
extern "C" void _M2_history_finish (void);
extern "C" void _M2_delay_init (int argc, char *argv[]);
extern "C" void _M2_delay_finish (void);
extern "C" void _M2_NetworkOrder_init (int argc, char *argv[]);
extern "C" void _M2_NetworkOrder_finish (void);
extern "C" void _M2_twoDsim_init (int argc, char *argv[]);
extern "C" void _M2_twoDsim_finish (void);
extern "C" void _M2_pgeif_init (int argc, char *argv[]);
extern "C" void _M2_pgeif_finish (void);

extern "C" void M2RTS_ExecuteInitialProcedures(void);

void __attribute__ ((constructor)) init (void);

void __attribute__ ((constructor)) init (void)
{
   try {
       _M2_Storage_init (0, (char **)0);
       _M2_SYSTEM_init (0, (char **)0);
       _M2_M2RTS_init (0, (char **)0);
       _M2_RTExceptions_init (0, (char **)0);
       _M2_IOLink_init (0, (char **)0);
       _M2_Indexing_init (0, (char **)0);
       _M2_NumberIO_init (0, (char **)0);
       _M2_StrLib_init (0, (char **)0);
       _M2_FIO_init (0, (char **)0);
       _M2_errno_init (0, (char **)0);
       _M2_termios_init (0, (char **)0);
       _M2_IO_init (0, (char **)0);
       _M2_StdIO_init (0, (char **)0);
       _M2_ErrnoCategory_init (0, (char **)0);
       _M2_Debug_init (0, (char **)0);
       _M2_IOConsts_init (0, (char **)0);
       _M2_RTio_init (0, (char **)0);
       _M2_SysExceptions_init (0, (char **)0);
       _M2_SysStorage_init (0, (char **)0);
       _M2_RTgen_init (0, (char **)0);
       _M2_RTgenif_init (0, (char **)0);
       _M2_ChanConsts_init (0, (char **)0);
       _M2_ASCII_init (0, (char **)0);
       _M2_M2EXCEPTION_init (0, (char **)0);
       _M2_StdChans_init (0, (char **)0);
       _M2_StrIO_init (0, (char **)0);
       _M2_RTentity_init (0, (char **)0);
       _M2_ldtoa_init (0, (char **)0);
       _M2_dtoa_init (0, (char **)0);
       _M2_Assertion_init (0, (char **)0);
       _M2_ConvTypes_init (0, (char **)0);
       _M2_IOChan_init (0, (char **)0);
       _M2_CharClass_init (0, (char **)0);
       _M2_EXCEPTIONS_init (0, (char **)0);
       _M2_DynamicStrings_init (0, (char **)0);
       _M2_WholeConv_init (0, (char **)0);
       _M2_StringConvert_init (0, (char **)0);
       _M2_gdbif_init (0, (char **)0);
       _M2_RTdata_init (0, (char **)0);
       _M2_WholeStr_init (0, (char **)0);
       _M2_wrapsock_init (0, (char **)0);
       _M2_wrapc_init (0, (char **)0);
       _M2_RTfio_init (0, (char **)0);
       _M2_GC_init (0, (char **)0);
       _M2_Strings_init (0, (char **)0);
       _M2_ComplexMath_init (0, (char **)0);
       _M2_Selective_init (0, (char **)0);
       _M2_coord_init (0, (char **)0);
       _M2_MathLib0_init (0, (char **)0);
       _M2_RawIO_init (0, (char **)0);
       _M2_Fractions_init (0, (char **)0);
       _M2_Builtins_init (0, (char **)0);
       _M2_roots_init (0, (char **)0);
       _M2_Points_init (0, (char **)0);
       _M2_ClientSocket_init (0, (char **)0);
       _M2_SeqFile_init (0, (char **)0);
       _M2_MemStream_init (0, (char **)0);
       _M2_deviceIf_init (0, (char **)0);
       _M2_polar_init (0, (char **)0);
       _M2_history_init (0, (char **)0);
       _M2_delay_init (0, (char **)0);
       _M2_NetworkOrder_init (0, (char **)0);
       _M2_twoDsim_init (0, (char **)0);
      M2RTS_ExecuteInitialProcedures ();
       _M2_pgeif_init (0, (char **)0);
    }
    catch (...) {
       RTExceptions_DefaultErrorCatch();
    }
}

void __attribute__ ((destructor)) finish (void);

void __attribute__ ((destructor)) finish (void)
{
   try {
      _M2_pgeif_finish ();
      _M2_twoDsim_finish ();
      _M2_NetworkOrder_finish ();
      _M2_delay_finish ();
      _M2_history_finish ();
      _M2_polar_finish ();
      _M2_deviceIf_finish ();
      _M2_MemStream_finish ();
      _M2_SeqFile_finish ();
      _M2_ClientSocket_finish ();
      _M2_Points_finish ();
      _M2_roots_finish ();
      _M2_Builtins_finish ();
      _M2_Fractions_finish ();
      _M2_RawIO_finish ();
      _M2_MathLib0_finish ();
      _M2_coord_finish ();
      _M2_Selective_finish ();
      _M2_ComplexMath_finish ();
      _M2_Strings_finish ();
      _M2_GC_finish ();
      _M2_RTfio_finish ();
      _M2_wrapc_finish ();
      _M2_wrapsock_finish ();
      _M2_WholeStr_finish ();
      _M2_RTdata_finish ();
      _M2_gdbif_finish ();
      _M2_StringConvert_finish ();
      _M2_WholeConv_finish ();
      _M2_DynamicStrings_finish ();
      _M2_EXCEPTIONS_finish ();
      _M2_CharClass_finish ();
      _M2_IOChan_finish ();
      _M2_ConvTypes_finish ();
      _M2_Assertion_finish ();
      _M2_dtoa_finish ();
      _M2_ldtoa_finish ();
      _M2_RTentity_finish ();
      _M2_StrIO_finish ();
      _M2_StdChans_finish ();
      _M2_M2EXCEPTION_finish ();
      _M2_ASCII_finish ();
      _M2_ChanConsts_finish ();
      _M2_RTgenif_finish ();
      _M2_RTgen_finish ();
      _M2_SysStorage_finish ();
      _M2_SysExceptions_finish ();
      _M2_RTio_finish ();
      _M2_IOConsts_finish ();
      _M2_Debug_finish ();
      _M2_ErrnoCategory_finish ();
      _M2_StdIO_finish ();
      _M2_IO_finish ();
      _M2_termios_finish ();
      _M2_errno_finish ();
      _M2_FIO_finish ();
      _M2_StrLib_finish ();
      _M2_NumberIO_finish ();
      _M2_Indexing_finish ();
      _M2_IOLink_finish ();
      _M2_RTExceptions_finish ();
      _M2_M2RTS_finish ();
      _M2_SYSTEM_finish ();
      _M2_Storage_finish ();
    }
    catch (...) {
       RTExceptions_DefaultErrorCatch();
    }
}
